name : :ab 3 Create Artifact

# Trigger
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


#Job
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # Check out our repository
    - uses: actions/checkout@v3

    # Use Node
    - name: Use Node.js 18.x 
      uses: actions/setup-node@v3
      with: 
        node-version: 18
    
    # Pretend build
    - name: Pretend to build
      run: echo Pretendd to build some kind of app...
    
    #Upload our file
    - name: Push our hello file
      uses: actions/upload-artifact@v3
      with: 
        name: My-Artifact
        path: Hello.txt
        if-no-files-found: error
  
  build:
    # Needs will make like a bridge
    # needs: test
    runs-on: ubuntu-latest
    steps:
      # Check out our repo
      - uses: action/checkout@v3

      # Test build
      - name: Building App
        run: echo I am building ... 